set(SPARTA_CXX_FLAGS "-DSPARTA_GZIP -DSPARTA_UNORDERED_MAP" CACHE STRING "")

set(CMAKE_CXX_COMPILER "c++" CACHE STRING "")
set(CMAKE_CXX_FLAGS "-O -fPIC ${SPARTA_CXX_FLAGS}" CACHE STRING "")

set(CMAKE_AR "ar" CACHE STRING "")
#set(CMAKE_STATIC_LINKER_FLAGS "-rc" CACHE STRING "")

set(CMAKE_SHARED_LINKER_FLAGS "-fPIC -shared" CACHE STRING "")

set(CMAKE_EXE_LINKER_FLAGS "-O" CACHE STRING "")
