/* ----------------------------------------------------------------------
   SPARTA - Stochastic PArallel Rarefied-gas Time-accurate Analyzer
   http://sparta.sandia.gov
   Steve Plimpton, sjplimp@sandia.gov, Michael Gallis, magalli@sandia.gov
   Sandia National Laboratories

   Copyright (2014) Sandia Corporation.  Under the terms of Contract
   DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government retains
   certain rights in this software.  This software is distributed under 
   the GNU General Public License.

   See the README file in the top-level SPARTA directory.
------------------------------------------------------------------------- */

#ifndef SPARTA_RESTART_MPIIO_H
#define SPARTA_RESTART_MPIIO_H

#include "pointers.h"

namespace SPARTA_NS {

class RestartMPIIO  : protected Pointers {
 private:
   MPI_File mpifh;
   int nprocs, myrank;

 public:
  int mpiio_exists;

  RestartMPIIO(class SPARTA *);
  ~RestartMPIIO() {}
  void openForRead(char *);
  void openForWrite(char *);
  void write(MPI_Offset, int, char *);
  void read(MPI_Offset, bigint, char *);
  void close();
};

}

#endif

/* ERROR/WARNING messages:

E: Cannot open restart file for reading - MPI error: %s

This error was generated by MPI when reading/writing an MPI-IO restart
file.

E: Cannot open restart file for writing - MPI error: %s

This error was generated by MPI when reading/writing an MPI-IO restart
file.

E: Cannot set restart file size - MPI error: %s

This error was generated by MPI when reading/writing an MPI-IO restart
file.

E: Cannot write to restart file - MPI error: %s

This error was generated by MPI when reading/writing an MPI-IO restart
file.

E: Cannot read from restart file - MPI error: %s

This error was generated by MPI when reading/writing an MPI-IO restart
file.

E: Cannot close restart file - MPI error: %s

This error was generated by MPI when reading/writing an MPI-IO restart
file.

*/
