# LAMMPS multiple-machine Makefile with explicit file list

SHELL = /bin/sh

# Definitions

ROOT =	dsmc
EXE =	$(ROOT)_$@

SRC =	dsmc.cpp error.cpp input.cpp library.cpp main.cpp memory.cpp random_mars.cpp random_park.cpp timer.cpp universe.cpp variable.cpp 

INC =	dsmc.h dsmctype.h error.h input.h library.h memory.h pointers.h random_mars.h random_park.h style_angle.h style_atom.h style_bond.h style_command.h style_compute.h style_dihedral.h style_dump.h style_fix.h style_improper.h style_integrate.h style_kspace.h style_minimize.h style_pair.h style_region.h timer.h universe.h variable.h version.h 

OBJ =	$(SRC:.cpp=.o)

# Targets

help:
	@echo 'Type "make target" where target is one of:'
	@echo ''
	@files="`ls MAKE/Makefile.*`"; \
	for file in $$files; do head -1 $$file; done

.DEFAULT:
	@test -f MAKE/Makefile.$@
	@if [ ! -d Obj_$@ ]; then mkdir Obj_$@; fi
	@cp -p $(SRC) $(INC) Obj_$@
	@cp MAKE/Makefile.$@ Obj_$@/Makefile
	@cd Obj_$@; \
	$(MAKE) $(MFLAGS) "OBJ = $(OBJ)" "INC = $(INC)" "EXE = ../$(EXE)" ../$(EXE)
	@if [ -d Obj_$@ ]; then cd Obj_$@; rm -f $(SRC) $(INC) Makefile*; fi
