# LAMMPS library multiple-machine Makefile

SHELL = /bin/sh

# Definitions

ROOT =	dsmc
EXE =	lib$(ROOT)_$@.a

SRC =	comm.cpp create_box.cpp domain.cpp dsmc.cpp error.cpp finish.cpp grid.cpp input.cpp library.cpp  memory.cpp output.cpp particle.cpp random_mars.cpp random_park.cpp run.cpp surf.cpp timer.cpp universe.cpp update.cpp variable.cpp velocity.cpp 

INC =	comm.h create_box.h domain.h dsmc.h dsmctype.h error.h finish.h grid.h input.h library.h memory.h output.h particle.h pointers.h random_mars.h random_park.h run.h style_command.h surf.h timer.h universe.h update.h variable.h velocity.h version.h 

OBJ =	$(SRC:.cpp=.o)

# Targets

help:
	@echo 'Type "make target" where target is one of:'
	@echo ''
	@files="`ls MAKE/Makefile.*`"; \
	for file in $$files; do head -1 $$file; done

clean:
	rm -rf Obj_*

.DEFAULT:
	@test -f MAKE/Makefile.$@
	@if [ ! -d Obj_$@ ]; then mkdir Obj_$@; fi
	@cp -p $(SRC) $(INC) Obj_$@
	@cp MAKE/Makefile.$@ Obj_$@/Makefile
	@cd Obj_$@; \
	$(MAKE) $(MFLAGS) "OBJ = $(OBJ)" "INC = $(INC)" "EXE = ../$(EXE)" lib
	@if [ -d Obj_$@ ]; then cd Obj_$@; rm -f $(SRC) $(INC) Makefile*; fi
